/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;
import java.io.IOException;
import java.net.MalformedURLException;


public class App {
    public void getGreeting() throws InterruptedException, IOException {
//        SearchAmazon  sa = new SearchAmazon();
//        sa.lanuchBrowser();
//        sa.searchAmazon();
//        sa.endTest();
//
//        BookMyShow_Hyperlinks BMS_H = new BookMyShow_Hyperlinks();
//        BMS_H.lanuchBrowser();
//        BMS_H.getLinks_count();
//        BMS_H.endTest();


//        Automate_nested_frames_text nestedFrame = new Automate_nested_frames_text();
//        nestedFrame.lanuchBrowser();
//        nestedFrame.getFrameName();
//        nestedFrame.endTest();

//        Automate_imdb_ratings ratings = new Automate_imdb_ratings();
//        ratings.lanuchBrowser();
//        ratings.getRating();
//        ratings.endTest();

//        Automate_window_handle windowHandle =new Automate_window_handle();
//        windowHandle.lanuchBrowser();
//        windowHandle.handleButtonClick();
//        windowHandle.endTest();

//        Automate_image_urls imageUrls = new Automate_image_urls();
//        imageUrls.lanuchBrowser();
//        imageUrls.img_url();
//        imageUrls.endTest()
//        ;

//        post_on_linkedin pol = new post_on_linkedin();
//        pol.lanuchBrowser();
//        pol.Post_on_linkedin();
//        pol.endTest();



    }



    public static void main(String[] args) throws InterruptedException, IOException {
        new App().getGreeting();
    }
}
